### ISSUE TITLE
Actions

### ISSUE THREAD

**Issue by cahidenes** [bounswe/bounswe2023group2#54] opened 2023-03-19 15:26 UTC
Action section of the requirements should contain:
- [ ] The attributes of the action that has been taken during the disaster such as location, type, provider...
- [ ] The usage of the action in the system

**Comment by arasgungore** [comment] 2023-03-20 10:52
Completed "Actions" section within System Requirements in [Requirements second version].(https://github.com/bounswe/bounswe2023group2/wiki/Requirement-draft-2)

**Comment by bgmrsln** [comment] 2023-03-20 19:14
I am not sure if it is okay to write "can" for requirements. I think it should be should or shall.

**Comment by mervegrbz** [comment] 2023-03-21 07:03
I agree @bgmrsln. Moreover actions are one of the key concepts of our project. We can also open a discussion for discussing  further

**Comment by cahidenes** [comment] 2023-03-21 07:45
> I am not sure if it is okay to write "can" for requirements. I think it should be should or shall.

I forgot to fix it sorry. It is fixed now.

> We can also open a discussion for discussing further

Opened a discussion [here](https://github.com/bounswe/bounswe2023group2/discussions/63)

**Comment by mehmetkuzu** [comment] 2023-03-22 08:18
Can should be replaced with shall be able to

Actions should be able to be edited and deleted by the creators. (Bu 4 madde için yukarıdaki yorumlar geçerli)

A better writing for this

Users shall be able to edit end delete the actions created by themselves.

(Shall is must, should is advised)

**Comment by mervegrbz** [comment] 2023-03-27 07:52
We have an initial completed requirements. We should revise all requirements as a whole. Since the issue is completed, I am closing.

**Closed by mervegrbz** 2023-03-27 07:52 UTC
